### ISSUE TITLE
write outputs to user specified directory

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-cat30#12] opened 2015-07-04 20:27 UTC
Running output via command line via `java -jar ets-cat30-${version}-aio.jar my-csw.xml` always writes out test outputs to a directory under `$HOME/testng/`.  Can this be modified via command line argument to write to a user specified directory?

**Comment by rjmartell** [comment] 2015-08-14 16:09
That would be straightforward. You may have noticed that the main method currently just uses the default location (`user.home`), but it could also be gleaned from a command line option.

e.g.
ets-cat30-${version}-aio.jar -o $TMPDIR my-csw.xml

**Comment by tomkralidis** [comment] 2015-08-15 16:52
No such luck against master:
```bash
$ java -jar ets-cat30/target/ets-cat30-0.9-SNAPSHOT-aio.jar -o foo/ csw3-run-props.xml 
Exception in thread "main" java.lang.IllegalArgumentException: Test run arguments not found at -o
	at org.opengis.cite.cat30.TestNGController.main(TestNGController.java:56)
```

Trying like this:

```bash
$ java -jar ets-cat30/target/ets-cat30-0.9-SNAPSHOT-aio.jar csw3-run-props.xml -o foo/
```

Runs as expected but `-o` is ignored.

**Comment by rjmartell** [comment] 2015-08-25 22:08
No changes committed yet. My example was intended as a proposal. If that option is fine I'll add it this week.

**Comment by tomkralidis** [comment] 2015-08-25 22:45
:+1:

**Comment by rjmartell** [comment] 2015-08-31 20:54
`ets-cat30-${version}-aio.jar [-o|--outputDir $TMPDIR] [test-run-props.xml]`

**Closed** 2015-08-31 20:54 UTC

**Comment by tomkralidis** [comment] 2015-08-31 22:25
works, thanks @rjmartell!
